version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sportedu_postgres
    environment:
      POSTGRES_DB: sportedudb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - sportedu_data:/var/lib/postgresql/data

volumes:
  sportedu_data:
